on: pull_request
name: Pull Request job
jobs:
  validate-tests:
    name: Prvi test
    runs-on: self-hosted
    steps:
    - name: Checkout 1.
      uses: actions/checkout@main
    - name: Kompajliram kod
      run: |
        ls
        echo "Sa Zadatak_1 repoa"
        echo Hello
        echo "Nazad"
        ls ../../..
        exit 1
