on: pull_request
name: Pull Request job
jobs:
  validate-tests:
    name: Prvi test
    runs-on: raspberry
    steps:
    - name: Checkout 1.
      uses: actions/checkout@main
    - name: Pokrecem test
      run: echo Hello

