on: pull_request
name: Pull Request
jobs:
  validate-tests:
    name: Run tests
    runs-on: raspberry
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Run your tests
      run: make tests
    - name: Validate Tests
      uses: quality-of-tests/has-useful-tests-action@main
      with:
        run-tests: echo Hello