on: pull_request
name: Pull Request job
jobs:
  validate-tests:
    name: Prvi test
    runs-on: self-hosted
    steps:
    - name: Checkout 1.
      uses: actions/checkout@main
    - name: Kompajliram kod
      run: |
        ls
        exit 1
    - name: Pokrecem testbench
        echo "Radi li"
